trigger:
 - master
 
pool: 

 name : Default

steps:
- script: echo Myfirst
  displayName : 'Run a one '

- script: mvn clean install
  displayName: 'Build with maven'

- script: java -jat target/MyMavenApp-1.0-SNAPSHOT.jar
  displayName: 'Running jar'
